/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxiagent007;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author kotaro and fabio :)
 */
public class MainPanel extends javax.swing.JFrame implements ActionListener {
    
    static int total_seconds = 0;
    static int seconds = 0;
    static int frame = 20;

    /**
     * Creates new form MainPanel
     * @param company
     */
    public MainPanel( Company company ) {
        this.company = company;
        initComponents();
        
        city = new City();
    
        city.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
       
        
    }
    
    public void setTaxiLabels(){
        taxi_labels = new javax.swing.JLabel[this.city.company.taxi_props.length][3];
        for( int i = 0 ; i < taxi_labels.length; i++ ){
            taxi_labels[i][0] = new javax.swing.JLabel();
            taxi_labels[i][1] = new javax.swing.JLabel();
            taxi_labels[i][2] = new javax.swing.JLabel();
            
            taxi_labels[i][0].setFont(new java.awt.Font("Tahoma", 1, 11));
            taxi_labels[i][0].setText("Taxi driver " + (i+1));
            taxi_labels[i][0].setForeground( (Color)this.city.company.taxi_props[i][2] );
            taxi_labels[i][1].setText(State.WAITING_FOR_COMPANY.name());
            taxi_labels[i][2].setText("Profit: NT$0");

        }
        
       
        javax.swing.GroupLayout taxi_state_panelLayout = new javax.swing.GroupLayout(taxi_state_panel);
        taxi_state_panel.setLayout(taxi_state_panelLayout);
        
        GroupLayout.SequentialGroup seq_group = taxi_state_panelLayout.createSequentialGroup()
                .addContainerGap();
        
        GroupLayout.ParallelGroup par_group = taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
                    
        for( javax.swing.JLabel[] labels : taxi_labels ){
            for( javax.swing.JLabel label : labels ){
                par_group.addComponent(label);
                seq_group.addComponent(label);
            }
            seq_group.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        } 
        
        seq_group.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        
        
        taxi_state_panelLayout.setHorizontalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxi_state_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(par_group).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        taxi_state_panelLayout.setVerticalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seq_group)
        );
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        anim_slider = new javax.swing.JSlider();
        animdelay_label = new javax.swing.JLabel();
        frame_slider = new javax.swing.JSlider();
        frame_label = new javax.swing.JLabel();
        taxi_state_panel = new javax.swing.JPanel();
        calls_label = new javax.swing.JLabel();
        company_label = new javax.swing.JLabel();
        company_state_label = new javax.swing.JLabel();
        company_profit_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        time_slider = new javax.swing.JSlider();
        time_label = new javax.swing.JLabel();
        totalminutes_label = new javax.swing.JLabel();
        lambda_label = new javax.swing.JLabel();
        poisson_label = new javax.swing.JLabel();
        chargekm_label = new javax.swing.JLabel();
        gaskm_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        anim_slider.setMaximum(1000);
        anim_slider.setMinimum(10);
        anim_slider.setValue(150);
        anim_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anim_sliderStateChanged(evt);
            }
        });

        animdelay_label.setText("Animation Delay: 150ms");

        frame_slider.setMaximum(90);
        frame_slider.setMinimum(1);
        frame_slider.setValue(20);
        frame_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frame_sliderStateChanged(evt);
            }
        });

        frame_label.setText("Frame: 20 seconds");

        taxi_state_panel.setBackground(new java.awt.Color(251, 250, 250));

        javax.swing.GroupLayout taxi_state_panelLayout = new javax.swing.GroupLayout(taxi_state_panel);
        taxi_state_panel.setLayout(taxi_state_panelLayout);
        taxi_state_panelLayout.setHorizontalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        taxi_state_panelLayout.setVerticalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        calls_label.setText("0 call(s)");

        company_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        company_label.setText("Taxi Agent Company");

        company_state_label.setText("WAITING_FOR_CALLS");

        company_profit_label.setText("Company Profit: NT$0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(frame_slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anim_slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(animdelay_label)
                            .addComponent(frame_label))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addComponent(taxi_state_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(company_label)
                    .addComponent(calls_label)
                    .addComponent(company_state_label)
                    .addComponent(company_profit_label))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_state_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calls_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_profit_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taxi_state_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frame_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frame_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(animdelay_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anim_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        time_slider.setMaximum(86399);
        time_slider.setValue(0);
        time_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                time_sliderStateChanged(evt);
            }
        });

        time_label.setText("12:00 A.M.");

        totalminutes_label.setText("0 second(s) in total");

        lambda_label.setText("λ = 1");

        poisson_label.setText("p(4) = 1");

        chargekm_label.setText("Charge/KM: NT$40");

        gaskm_label.setText("Gas/KM: NT$6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(time_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(totalminutes_label))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lambda_label)
                            .addComponent(poisson_label)
                            .addComponent(chargekm_label)
                            .addComponent(gaskm_label))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lambda_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poisson_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chargekm_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaskm_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(time_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label)
                    .addComponent(totalminutes_label))
                .addContainerGap())
        );

        totalminutes_label.getAccessibleContext().setAccessibleName("totalminutes_label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.startAnimation();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.stopAnimation();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void time_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_time_sliderStateChanged
        
        if( MainPanel.seconds < this.time_slider.getValue() )
            MainPanel.total_seconds += (this.time_slider.getValue() - MainPanel.seconds);
        
        MainPanel.seconds = this.time_slider.getValue();
        
        //set lambda
        if( MainPanel.seconds >= 25200 && MainPanel.seconds <= 32400 )// 7am - 9am
            city.lambda = 3;
        else if( MainPanel.seconds >= 61200 && MainPanel.seconds <= 68400 )// 5pm - 7pm
            city.lambda = 3;
        else if( MainPanel.seconds > 32400 && MainPanel.seconds <= 61200 )// 9am - 5pm
            city.lambda = 2;
        else if( MainPanel.seconds > 68400 && MainPanel.seconds <= 82800 ) //7pm - 11pm
            city.lambda = 2;
        else
            city.lambda = 1;
        
        this.updateLabels();
    }//GEN-LAST:event_time_sliderStateChanged

    private void anim_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anim_sliderStateChanged
        this.city_timer.setInitialDelay( this.anim_slider.getValue() );
        this.city_timer.setDelay( this.anim_slider.getValue() );
        this.city_timer.restart();
        this.updateLabels();
    }//GEN-LAST:event_anim_sliderStateChanged

    private void frame_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frame_sliderStateChanged
        MainPanel.frame = this.frame_slider.getValue();
        this.updateLabels();
    }//GEN-LAST:event_frame_sliderStateChanged

    private void updateLabels(){
        
        //time label
        int hour = ((MainPanel.seconds/60)/60)%12;
        if( hour == 0 )
            hour = 12;
        int minutes = (MainPanel.seconds/60)%60;
        int secs = MainPanel.seconds%60;
        String xm = (MainPanel.seconds<60*60*12)?"A.M.":"P.M.";
        
        this.time_label.setText( (hour<10?"0":"") + hour + ":" + (minutes<10?"0":"") + minutes + ":" + (secs<10?"0":"") + secs + " " + xm );
        
        //variable label
        this.lambda_label.setText( "λ = " + this.city.lambda);
        this.poisson_label.setText( "p(" + this.city.k + ") = " + city.poisson(this.city.k ) );
        this.calls_label.setText(city.totalCalls + " call(s)");
        this.totalminutes_label.setText( MainPanel.total_seconds + " second(s) in total");
        this.animdelay_label.setText( "Animation delay: " + this.anim_slider.getValue() + "ms");
        this.frame_label.setText( "Frame: " + MainPanel.frame + " seconds");
        this.gaskm_label.setText("Gas/KM: NT$" + this.company.gas_cost_km*7);
        this.chargekm_label.setText("Charge/KM: NT$" + this.company.charge_rate_km*7);
        
        //taxi labels
        for( int i = 0 ; i < this.taxi_labels.length ; i++ ){
            taxi_labels[i][2].setText("Profit: NT$" + this.company.taxis.get(i).driver.profit );
            taxi_labels[i][1].setText( this.company.taxis.get(i).driver.state.name() );
        }
        
        //company labels
        this.company_profit_label.setText("Company Profit: NT$" + this.company.profit );
        this.company_state_label.setText(this.company.state.name());
        
    }
    
    private void update(){
        if( this.running ){
            city.updateCity();
            
            if( MainPanel.seconds >= this.time_slider.getMaximum() ){
                this.time_slider.setValue( 0 );
            }else{
                this.time_slider.setValue( MainPanel.seconds + MainPanel.frame );
            }
            
            /*if( (MainPanel.seconds%(60*60)) == 0 ){
                city.resolveAll();
            }*/
            
            this.updateLabels();
        }
    }
    
    private void startAnimation(){
       this.running = true;
    }
    
    private void stopAnimation(){
        this.running = false;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        this.update();
        this.city.paint(this.city.getGraphics());
    }
    
    private void initAnimation(){
        this.running = false;
        city_timer = new Timer(this.anim_slider.getValue(), this);
        city_timer.start();
    }
    
    private void console_log( String text ){
        this.text2write = text;
        this.characters = 0;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainPanel window = new MainPanel( MainPanel.st_company );
                
                window.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) 
                    {
                        /* code run when component hidden*/
                    }
                    @Override
                    public void componentShown(ComponentEvent e) {
                        window.company.onPanelReady(window);
                    }
                });
                
                window.setVisible(true);
                window.initAnimation();
            }
         
        });
    }
    
    public static void jade_main(Company company) {
        MainPanel.st_company = company;
        MainPanel.main(null);
    }
    
    static Company st_company;
    private Company company;
    private Timer city_timer;
    public boolean running;
    public City city;
    String text2write = "";
    int characters = 0;
    private javax.swing.JLabel[][] taxi_labels;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider anim_slider;
    private javax.swing.JLabel animdelay_label;
    private javax.swing.JLabel calls_label;
    private javax.swing.JLabel chargekm_label;
    private javax.swing.JLabel company_label;
    private javax.swing.JLabel company_profit_label;
    private javax.swing.JLabel company_state_label;
    private javax.swing.JLabel frame_label;
    private javax.swing.JSlider frame_slider;
    private javax.swing.JLabel gaskm_label;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lambda_label;
    private javax.swing.JLabel poisson_label;
    private javax.swing.JPanel taxi_state_panel;
    private javax.swing.JLabel time_label;
    private javax.swing.JSlider time_slider;
    private javax.swing.JLabel totalminutes_label;
    // End of variables declaration//GEN-END:variables
}
