/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxiagent007;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.GroupLayout;
import javax.swing.Timer;

/**
 *
 * @author kotaro and fabio :)
 */
public class MainPanel extends javax.swing.JFrame implements ActionListener {
    
    static int total_seconds = 0;
    static int seconds = 0;
    static int frame = 20;
    static Company st_company;
    
    private final Company company;
    private Timer city_timer;
    public boolean running;
    public City city;
    String text2write = "";
    int characters = 0;
    private javax.swing.JLabel[][] taxi_labels;

    /**
     * Creates new form MainPanel
     * @param company
     */
    public MainPanel( Company company ) {
        this.company = company;
        initComponents();
        
        city = new City();
    
        city.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
       
        
    }
    
    public void setTaxiLabels(){
        taxi_labels = new javax.swing.JLabel[this.city.company.taxi_props.length][4];
        for( int i = 0 ; i < taxi_labels.length; i++ ){
            taxi_labels[i][0] = new javax.swing.JLabel();
            taxi_labels[i][1] = new javax.swing.JLabel();
            taxi_labels[i][2] = new javax.swing.JLabel();
            taxi_labels[i][3] = new javax.swing.JLabel();
            
            taxi_labels[i][0].setFont(new java.awt.Font("Tahoma", 1, 11));
            taxi_labels[i][0].setText("Taxi driver " + (i+1));
            taxi_labels[i][0].setForeground( (Color)this.city.company.taxi_props[i][2] );

            taxi_labels[i][1].setText("Own: NT$0  Next:");
            taxi_labels[i][2].setText("Customer:");
            taxi_labels[i][3].setText("Bid: NT$0 Max: NT$0");
        }
        
        for( javax.swing.JLabel[] labels : taxi_labels ){
            for( javax.swing.JLabel label : labels )
                label.setVisible(false);
        }
                    
        
        javax.swing.GroupLayout taxi_state_panelLayout = new javax.swing.GroupLayout(taxi_state_panel);
        taxi_state_panel.setLayout(taxi_state_panelLayout);
    
        
        GroupLayout.SequentialGroup seq_group = taxi_state_panelLayout.createSequentialGroup()
                .addContainerGap();
        
        GroupLayout.ParallelGroup par_group = taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
                    
        for( javax.swing.JLabel[] labels : taxi_labels ){
            for( javax.swing.JLabel label : labels ){
                par_group.addComponent(label);
                seq_group.addComponent(label);
            }
            seq_group.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED);
        } 
        
        seq_group.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
        
        
        taxi_state_panelLayout.setHorizontalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxi_state_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(par_group).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        taxi_state_panelLayout.setVerticalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seq_group)
        );
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        play_btn = new javax.swing.JButton();
        taxi_state_panel = new javax.swing.JPanel();
        calls_label = new javax.swing.JLabel();
        company_label = new javax.swing.JLabel();
        company_state_label = new javax.swing.JLabel();
        company_profit_label = new javax.swing.JLabel();
        force_call_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        time_slider = new javax.swing.JSlider();
        time_label = new javax.swing.JLabel();
        totalminutes_label = new javax.swing.JLabel();
        lambda_label = new javax.swing.JLabel();
        poisson_label = new javax.swing.JLabel();
        chargekm_label = new javax.swing.JLabel();
        gaskm_label = new javax.swing.JLabel();
        frame_label = new javax.swing.JLabel();
        frame_slider = new javax.swing.JSlider();
        animdelay_label = new javax.swing.JLabel();
        anim_slider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taxi Agent 007");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        play_btn.setText("Start");
        play_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_btnActionPerformed(evt);
            }
        });

        taxi_state_panel.setBackground(new java.awt.Color(243, 240, 235));

        javax.swing.GroupLayout taxi_state_panelLayout = new javax.swing.GroupLayout(taxi_state_panel);
        taxi_state_panel.setLayout(taxi_state_panelLayout);
        taxi_state_panelLayout.setHorizontalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        taxi_state_panelLayout.setVerticalGroup(
            taxi_state_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        calls_label.setText("0 call(s)");

        company_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        company_label.setText("Taxi Agent Company");

        company_state_label.setText("WAITING_FOR_CALLS");

        company_profit_label.setText("Company Profit: NT$0");

        force_call_btn.setText("force call");
        force_call_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                force_call_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxi_state_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(company_label)
                            .addComponent(calls_label)
                            .addComponent(company_state_label)
                            .addComponent(company_profit_label)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(play_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(force_call_btn)))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play_btn)
                    .addComponent(force_call_btn))
                .addGap(11, 11, 11)
                .addComponent(company_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_state_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calls_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_profit_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taxi_state_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        time_slider.setMaximum(86399);
        time_slider.setValue(0);
        time_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                time_sliderStateChanged(evt);
            }
        });

        time_label.setText("12:00 A.M.");

        totalminutes_label.setText("0 second(s) in total");

        lambda_label.setText("λ = 1");

        poisson_label.setText("p(4) = 1");

        chargekm_label.setText("Charge/KM: NT$40");

        gaskm_label.setText("Gas/KM: NT$6");

        frame_label.setText("Frame: 20 seconds");

        frame_slider.setMaximum(90);
        frame_slider.setMinimum(1);
        frame_slider.setValue(20);
        frame_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                frame_sliderStateChanged(evt);
            }
        });

        animdelay_label.setText("Animation Delay: 150ms");

        anim_slider.setMaximum(1000);
        anim_slider.setMinimum(10);
        anim_slider.setValue(150);
        anim_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                anim_sliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(time_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lambda_label)
                        .addGap(104, 104, 104)
                        .addComponent(frame_label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poisson_label)
                            .addComponent(chargekm_label)
                            .addComponent(gaskm_label))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(animdelay_label)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(frame_slider, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                            .addComponent(anim_slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(time_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalminutes_label)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lambda_label)
                    .addComponent(frame_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poisson_label)
                    .addComponent(frame_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chargekm_label)
                    .addComponent(animdelay_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anim_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaskm_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time_label)
                    .addComponent(totalminutes_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(time_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalminutes_label.getAccessibleContext().setAccessibleName("totalminutes_label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void play_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_btnActionPerformed

        if( this.running ){
            this.stopAnimation();
            this.play_btn.setText("Continue");
        }else{
            this.startAnimation();
            this.play_btn.setText("Pause");
        }
        
    }//GEN-LAST:event_play_btnActionPerformed

    private void force_call_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_force_call_btnActionPerformed
        this.city.makeCall();
    }//GEN-LAST:event_force_call_btnActionPerformed

    private void anim_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_anim_sliderStateChanged
        this.city_timer.setInitialDelay( this.anim_slider.getValue() );
        this.city_timer.setDelay( this.anim_slider.getValue() );
        this.city_timer.restart();
        this.updateLabels();
    }//GEN-LAST:event_anim_sliderStateChanged

    private void frame_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_frame_sliderStateChanged
        MainPanel.frame = this.frame_slider.getValue();
        this.updateLabels();
    }//GEN-LAST:event_frame_sliderStateChanged

    private void time_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_time_sliderStateChanged

        if( MainPanel.seconds < this.time_slider.getValue() )
        MainPanel.total_seconds += (this.time_slider.getValue() - MainPanel.seconds);

        MainPanel.seconds = this.time_slider.getValue();

        //set lambda
        if( MainPanel.seconds >= 25200 && MainPanel.seconds <= 32400 )// 7am - 9am
        city.lambda = 3;
        else if( MainPanel.seconds >= 61200 && MainPanel.seconds <= 68400 )// 5pm - 7pm
        city.lambda = 3;
        else if( MainPanel.seconds > 32400 && MainPanel.seconds <= 61200 )// 9am - 5pm
        city.lambda = 2;
        else if( MainPanel.seconds > 68400 && MainPanel.seconds <= 82800 ) //7pm - 11pm
        city.lambda = 2;
        else
        city.lambda = 1;

        this.updateLabels();
    }//GEN-LAST:event_time_sliderStateChanged

    private void updateLabels(){
        
        //time label
        int hour = ((MainPanel.seconds/60)/60)%12;
        if( hour == 0 )
            hour = 12;
        int minutes = (MainPanel.seconds/60)%60;
        int secs = MainPanel.seconds%60;
        String xm = (MainPanel.seconds<60*60*12)?"A.M.":"P.M.";
        
        this.time_label.setText( (hour<10?"0":"") + hour + ":" + (minutes<10?"0":"") + minutes + ":" + (secs<10?"0":"") + secs + " " + xm );
        
        //variable label
        this.lambda_label.setText( "λ = " + this.city.lambda);
        this.poisson_label.setText( "p(" + this.city.k + ") = " + city.poisson(this.city.k ) );
        this.calls_label.setText(city.totalCalls + " call(s) (" + city.callsHour + " call(s) in last hour)" );
        
        int days = MainPanel.total_seconds/86400;
        int hours = (MainPanel.total_seconds%86400)/3600;
        
        
        this.totalminutes_label.setText( days + " day(s) " + hours + " hour(s) in total");
        this.animdelay_label.setText( "Animation delay: " + this.anim_slider.getValue() + "ms");
        this.frame_label.setText( "Frame: " + MainPanel.frame + " seconds");
        this.gaskm_label.setText("Gas/KM: NT$" + this.company.gas_cost_km*7);
        this.chargekm_label.setText("Charge/KM: NT$" + this.company.charge_rate_km*7);
        
        //taxi labels
        String requests = null;
        String customer = null;
        for( int i = 0 ; i < this.taxi_labels.length ; i++ ){
            Taxi taxi = this.company.taxis.get(i);
            if( taxi.driver.state != State.OUT_OF_SERVICE ){
            
                for( javax.swing.JLabel label : taxi_labels[i] )
                    label.setVisible(true);
                
                requests = "";
                customer = "";
                for( int j = 0 ; j < taxi.driver.requests.size() ; j++ )
                    requests +=  "P" + taxi.driver.requests.get(j).passenger_id + ((j!=taxi.driver.requests.size()-1)?", ":"");

                if( taxi.driver.actual_request != null){
                    customer = "P" + taxi.driver.actual_request.passenger_id + "( NTD$" + ((int)taxi.driver.actual_request.price) +
                            ", NTD$" + ((int)taxi.driver.actual_request.company_cut)  + ")" ;
                }

                if( taxi.driver.cantBidIn != 0 )
                    taxi_labels[i][0].setText("Taxi driver " + (i+1) + " ( Cant Bid: " + taxi.driver.cantBidIn + "s )");
                else
                    taxi_labels[i][0].setText("Taxi driver " + (i+1));
                
                taxi_labels[i][3].setText("Bid: NT$" + ((int)taxi.driver.last_max_bid) + " Max: NT$" + ((int)taxi.driver.last_profit));
                taxi_labels[i][2].setText("Customer:" + customer );
                taxi_labels[i][1].setText("Profit: NT$" + taxi.driver.profit + "  Next: " + requests );
  
            }else{
                for( javax.swing.JLabel label : taxi_labels[i] )
                    label.setVisible(false);
            }
        }
        
        //company labels
        this.company_profit_label.setText("Company Profit: NT$" + this.company.profit );
        this.company_state_label.setText(this.company.state.name());
        
    }
    
    private void update(){
        if( this.running ){
            city.updateCity();
            
            if( MainPanel.seconds >= this.time_slider.getMaximum() ){
                this.time_slider.setValue( 0 );
            }else{
                this.time_slider.setValue( MainPanel.seconds + MainPanel.frame );
            }
            
            /*if( (MainPanel.seconds%(60*60)) == 0 ){
                city.resolveAll();
            }*/
            
            this.updateLabels();
        }
    }
    
    private void startAnimation(){
       this.running = true;
    }
    
    private void stopAnimation(){
        this.running = false;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        this.update();
        this.city.repaint();
    }
    
    private void initAnimation(){
        this.running = false;
        city_timer = new Timer(this.anim_slider.getValue(), this);
        city_timer.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainPanel window = new MainPanel( MainPanel.st_company );
                
                window.addComponentListener(new ComponentAdapter() {
                    @Override
                    public void componentHidden(ComponentEvent e) 
                    {
                        /* code run when component hidden*/
                    }
                    @Override
                    public void componentShown(ComponentEvent e) {
                        window.company.onPanelReady(window);
                    }
                });
                
                window.setVisible(true);
                window.initAnimation();
            }
         
        });
    }
    
    public static void jade_main(Company company) {
        MainPanel.st_company = company;
        MainPanel.main(null);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider anim_slider;
    private javax.swing.JLabel animdelay_label;
    private javax.swing.JLabel calls_label;
    private javax.swing.JLabel chargekm_label;
    private javax.swing.JLabel company_label;
    private javax.swing.JLabel company_profit_label;
    private javax.swing.JLabel company_state_label;
    private javax.swing.JButton force_call_btn;
    private javax.swing.JLabel frame_label;
    private javax.swing.JSlider frame_slider;
    private javax.swing.JLabel gaskm_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lambda_label;
    private javax.swing.JButton play_btn;
    private javax.swing.JLabel poisson_label;
    private javax.swing.JPanel taxi_state_panel;
    private javax.swing.JLabel time_label;
    private javax.swing.JSlider time_slider;
    private javax.swing.JLabel totalminutes_label;
    // End of variables declaration//GEN-END:variables
}
